-- S1-02 RBAC foundation: role_permissions gains an explicit resource_scope
-- per granted cell (tenant | assigned | quality_control). Cell semantics and
-- exact counts come from RBAC_MATRIX_V1 (src/authz/rbac-matrix.ts), which is
-- the single source of truth. See scripts/generate-rbac-seed-sql.cjs.
SET ROLE tallermecario_schema_owner;
--> statement-breakpoint

ALTER TABLE "role_permissions" ADD COLUMN "resource_scope" varchar(16) NOT NULL;
--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_resource_scope_check" CHECK ("resource_scope" IN ('tenant', 'assigned', 'quality_control'));
--> statement-breakpoint
-- BEGIN GENERATED RBAC V1

-- Roles baseline (system roles). Idempotente: no crea filas nuevas si ya
-- existen (código estable); actualiza nombre/scope/is_system si difieren.
INSERT INTO public.roles (id, code, name, scope, is_system) VALUES
	(uuidv7(), 'owner', 'Owner', 'tenant', true),
	(uuidv7(), 'admin', 'Administrador', 'tenant', true),
	(uuidv7(), 'service_advisor', 'Asesor de servicio', 'tenant', true),
	(uuidv7(), 'technician', 'Técnico', 'tenant', true)
ON CONFLICT (code) DO UPDATE SET
	name = EXCLUDED.name,
	scope = EXCLUDED.scope,
	is_system = EXCLUDED.is_system;
--> statement-breakpoint

-- Catálogo de permission codes (103 filas, RBAC_MATRIX_V1).
INSERT INTO public.permissions (id, code, description) VALUES
	(uuidv7(), 'workshop.read', 'Leer datos del taller (tenant).'),
	(uuidv7(), 'workshop.profile.update', 'Actualizar perfil del taller.'),
	(uuidv7(), 'workshop.legal.update', 'Actualizar datos legales del taller.'),
	(uuidv7(), 'locations.read', 'Leer ubicaciones del taller.'),
	(uuidv7(), 'locations.manage', 'Gestionar ubicaciones del taller.'),
	(uuidv7(), 'memberships.read', 'Leer memberships del taller.'),
	(uuidv7(), 'memberships.invite_staff', 'Invitar personal (membership_invitations).'),
	(uuidv7(), 'memberships.manage_staff', 'Gestionar/revocar memberships de personal.'),
	(uuidv7(), 'roles.assign_staff', 'Asignar roles service_advisor/technician.'),
	(uuidv7(), 'roles.assign_admin', 'Asignar/revocar rol admin.'),
	(uuidv7(), 'roles.assign_owner', 'Asignar/revocar rol owner.'),
	(uuidv7(), 'ownership.transfer', 'Transferir propiedad del taller.'),
	(uuidv7(), 'audit.read', 'Leer audit_logs del tenant.'),
	(uuidv7(), 'customers.read', 'Leer clientes.'),
	(uuidv7(), 'customers.create', 'Crear clientes.'),
	(uuidv7(), 'customers.update', 'Actualizar clientes.'),
	(uuidv7(), 'customers.archive', 'Archivar clientes.'),
	(uuidv7(), 'vehicles.read', 'Leer vehículos.'),
	(uuidv7(), 'vehicles.create', 'Crear vehículos.'),
	(uuidv7(), 'vehicles.update', 'Actualizar vehículos.'),
	(uuidv7(), 'vehicle_owners.manage', 'Gestionar relación vehículo-propietario.'),
	(uuidv7(), 'appointments.read', 'Leer citas de agenda.'),
	(uuidv7(), 'appointments.manage', 'Gestionar citas de agenda.'),
	(uuidv7(), 'receptions.read', 'Leer recepciones.'),
	(uuidv7(), 'receptions.create', 'Crear recepciones.'),
	(uuidv7(), 'receptions.update_open', 'Actualizar recepción abierta.'),
	(uuidv7(), 'receptions.close', 'Cerrar recepción.'),
	(uuidv7(), 'receptions.reopen', 'Reabrir recepción.'),
	(uuidv7(), 'signatures.capture', 'Capturar firmas.'),
	(uuidv7(), 'signatures.read', 'Leer firmas.'),
	(uuidv7(), 'media.read', 'Leer media.'),
	(uuidv7(), 'media.upload', 'Subir media.'),
	(uuidv7(), 'media.remove_unattached', 'Eliminar media no adjunta.'),
	(uuidv7(), 'orders.read', 'Leer órdenes de trabajo.'),
	(uuidv7(), 'orders.create', 'Crear órdenes de trabajo.'),
	(uuidv7(), 'orders.transition', 'Transicionar estado de orden.'),
	(uuidv7(), 'orders.assign', 'Asignar orden a membership.'),
	(uuidv7(), 'orders.cancel', 'Cancelar orden.'),
	(uuidv7(), 'orders.reopen', 'Reabrir orden.'),
	(uuidv7(), 'order_items.read', 'Leer líneas de orden.'),
	(uuidv7(), 'order_items.adjust_before_completion', 'Ajustar líneas antes de finalización.'),
	(uuidv7(), 'warranty.override_before_completion', 'Anular garantía antes de finalización.'),
	(uuidv7(), 'warranty.correct_after_completion', 'Corregir garantía tras finalización.'),
	(uuidv7(), 'diagnostics.read', 'Leer diagnóstico.'),
	(uuidv7(), 'diagnostics.write', 'Escribir diagnóstico.'),
	(uuidv7(), 'diagnostics.close', 'Cerrar diagnóstico.'),
	(uuidv7(), 'catalog.read', 'Leer catálogo.'),
	(uuidv7(), 'catalog.manage', 'Gestionar catálogo.'),
	(uuidv7(), 'inventory.read', 'Leer inventario.'),
	(uuidv7(), 'inventory.movements.read', 'Leer movimientos de inventario.'),
	(uuidv7(), 'inventory.receive', 'Registrar recepción de inventario.'),
	(uuidv7(), 'inventory.adjust', 'Ajustar inventario.'),
	(uuidv7(), 'inventory.transfer', 'Transferir inventario entre ubicaciones.'),
	(uuidv7(), 'inventory.consume_assigned', 'Consumir/retornar repuestos de orden asignada.'),
	(uuidv7(), 'quotes.propose_labor_adjustment', 'Proponer cotización supplemental de labor.'),
	(uuidv7(), 'quotes.read', 'Leer cotizaciones.'),
	(uuidv7(), 'quotes.create', 'Crear cotizaciones.'),
	(uuidv7(), 'quotes.update_draft', 'Actualizar cotización en borrador.'),
	(uuidv7(), 'quotes.override_price', 'Anular precio de cotización.'),
	(uuidv7(), 'quotes.send', 'Enviar cotización.'),
	(uuidv7(), 'quote_authorizations.read', 'Leer autorizaciones de cotización.'),
	(uuidv7(), 'quote_authorizations.record_manual', 'Registrar autorización manual/presencial.'),
	(uuidv7(), 'work_activities.read', 'Leer actividades de reparación.'),
	(uuidv7(), 'work_activities.manage', 'Gestionar actividades de reparación.'),
	(uuidv7(), 'technician_logs.read', 'Leer bitácora técnica.'),
	(uuidv7(), 'technician_logs.create', 'Crear entrada de bitácora técnica.'),
	(uuidv7(), 'quality_checks.read', 'Leer controles de calidad.'),
	(uuidv7(), 'quality_checks.perform', 'Ejecutar control de calidad.'),
	(uuidv7(), 'deliveries.read', 'Leer entregas.'),
	(uuidv7(), 'deliveries.complete', 'Completar entrega.'),
	(uuidv7(), 'customer_payments.read', 'Leer pagos del cliente.'),
	(uuidv7(), 'customer_payments.record', 'Registrar pago del cliente.'),
	(uuidv7(), 'customer_payments.allocate', 'Asignar (allocate) pago del cliente.'),
	(uuidv7(), 'customer_payments.reverse', 'Reversar pago del cliente.'),
	(uuidv7(), 'customer_payment_reconciliation.read', 'Leer conciliación de pagos.'),
	(uuidv7(), 'customer_payment_reconciliation.run', 'Ejecutar conciliación de pagos.'),
	(uuidv7(), 'customer_access_tokens.read', 'Leer tokens de acceso público del cliente.'),
	(uuidv7(), 'customer_access_tokens.create', 'Emitir token de acceso público del cliente.'),
	(uuidv7(), 'customer_access_tokens.revoke', 'Revocar token de acceso público del cliente.'),
	(uuidv7(), 'messages.read', 'Leer mensajes.'),
	(uuidv7(), 'messages.send', 'Enviar mensajes.'),
	(uuidv7(), 'reminders.manage', 'Gestionar recordatorios.'),
	(uuidv7(), 'privacy_consents.read', 'Leer consentimientos de privacidad.'),
	(uuidv7(), 'privacy_consents.capture', 'Capturar consentimiento de privacidad.'),
	(uuidv7(), 'data_subject_requests.create', 'Crear solicitud de titular de datos.'),
	(uuidv7(), 'data_subject_requests.read', 'Leer solicitudes de titular de datos.'),
	(uuidv7(), 'data_subject_requests.resolve', 'Resolver solicitud de titular de datos.'),
	(uuidv7(), 'privacy_data.export', 'Exportar datos personales.'),
	(uuidv7(), 'privacy_data.anonymize_or_delete', 'Anonimizar/eliminar datos personales.'),
	(uuidv7(), 'privacy_incidents.manage', 'Gestionar incidentes de privacidad/seguridad.'),
	(uuidv7(), 'subscription.read', 'Leer suscripción SaaS.'),
	(uuidv7(), 'subscription.manage', 'Gestionar suscripción SaaS.'),
	(uuidv7(), 'legal_acceptances.read', 'Leer aceptaciones legales.'),
	(uuidv7(), 'legal_acceptances.accept_for_tenant', 'Aceptar documentos legales por el tenant.'),
	(uuidv7(), 'dashboard.operational.read', 'Leer dashboard operacional.'),
	(uuidv7(), 'dashboard.business.read', 'Leer dashboard comercial/financiero.'),
	(uuidv7(), 'reports.operational.read', 'Leer reportes operativos.'),
	(uuidv7(), 'reports.financial.read', 'Leer reportes financieros.'),
	(uuidv7(), 'exports.operational.create', 'Crear exports operativos.'),
	(uuidv7(), 'notifications.read', 'Leer notificaciones propias.'),
	(uuidv7(), 'notifications.preferences.update_self', 'Actualizar preferencias propias de notificación.'),
	(uuidv7(), 'integrations.read', 'Leer integraciones del tenant.'),
	(uuidv7(), 'integrations.manage', 'Gestionar integraciones del tenant.')
ON CONFLICT (code) DO UPDATE SET
	description = EXCLUDED.description;
--> statement-breakpoint

-- Fail-fast: si una fila (role_id, permission_id) ya existe con un
-- resource_scope distinto al canónico, abortar en vez de sobrescribir o
-- ignorar silenciosamente (DO NOTHING nunca oculta un scope incorrecto).
DO $rbac_scope_drift_guard$
DECLARE
	v_mismatched integer;
BEGIN
	SELECT count(*) INTO v_mismatched
	FROM (
	VALUES
		('workshop.read', 'owner', 'tenant'),
		('workshop.read', 'admin', 'tenant'),
		('workshop.read', 'service_advisor', 'tenant'),
		('workshop.read', 'technician', 'tenant'),
		('workshop.profile.update', 'owner', 'tenant'),
		('workshop.profile.update', 'admin', 'tenant'),
		('workshop.legal.update', 'owner', 'tenant'),
		('locations.read', 'owner', 'tenant'),
		('locations.read', 'admin', 'tenant'),
		('locations.read', 'service_advisor', 'tenant'),
		('locations.read', 'technician', 'tenant'),
		('locations.manage', 'owner', 'tenant'),
		('locations.manage', 'admin', 'tenant'),
		('memberships.read', 'owner', 'tenant'),
		('memberships.read', 'admin', 'tenant'),
		('memberships.invite_staff', 'owner', 'tenant'),
		('memberships.invite_staff', 'admin', 'tenant'),
		('memberships.manage_staff', 'owner', 'tenant'),
		('memberships.manage_staff', 'admin', 'tenant'),
		('roles.assign_staff', 'owner', 'tenant'),
		('roles.assign_staff', 'admin', 'tenant'),
		('roles.assign_admin', 'owner', 'tenant'),
		('roles.assign_owner', 'owner', 'tenant'),
		('ownership.transfer', 'owner', 'tenant'),
		('audit.read', 'owner', 'tenant'),
		('audit.read', 'admin', 'tenant'),
		('customers.read', 'owner', 'tenant'),
		('customers.read', 'admin', 'tenant'),
		('customers.read', 'service_advisor', 'tenant'),
		('customers.create', 'owner', 'tenant'),
		('customers.create', 'admin', 'tenant'),
		('customers.create', 'service_advisor', 'tenant'),
		('customers.update', 'owner', 'tenant'),
		('customers.update', 'admin', 'tenant'),
		('customers.update', 'service_advisor', 'tenant'),
		('customers.archive', 'owner', 'tenant'),
		('customers.archive', 'admin', 'tenant'),
		('vehicles.read', 'owner', 'tenant'),
		('vehicles.read', 'admin', 'tenant'),
		('vehicles.read', 'service_advisor', 'tenant'),
		('vehicles.read', 'technician', 'assigned'),
		('vehicles.create', 'owner', 'tenant'),
		('vehicles.create', 'admin', 'tenant'),
		('vehicles.create', 'service_advisor', 'tenant'),
		('vehicles.update', 'owner', 'tenant'),
		('vehicles.update', 'admin', 'tenant'),
		('vehicles.update', 'service_advisor', 'tenant'),
		('vehicle_owners.manage', 'owner', 'tenant'),
		('vehicle_owners.manage', 'admin', 'tenant'),
		('vehicle_owners.manage', 'service_advisor', 'tenant'),
		('appointments.read', 'owner', 'tenant'),
		('appointments.read', 'admin', 'tenant'),
		('appointments.read', 'service_advisor', 'tenant'),
		('appointments.manage', 'owner', 'tenant'),
		('appointments.manage', 'admin', 'tenant'),
		('appointments.manage', 'service_advisor', 'tenant'),
		('receptions.read', 'owner', 'tenant'),
		('receptions.read', 'admin', 'tenant'),
		('receptions.read', 'service_advisor', 'tenant'),
		('receptions.read', 'technician', 'assigned'),
		('receptions.create', 'owner', 'tenant'),
		('receptions.create', 'admin', 'tenant'),
		('receptions.create', 'service_advisor', 'tenant'),
		('receptions.update_open', 'owner', 'tenant'),
		('receptions.update_open', 'admin', 'tenant'),
		('receptions.update_open', 'service_advisor', 'tenant'),
		('receptions.close', 'owner', 'tenant'),
		('receptions.close', 'admin', 'tenant'),
		('receptions.close', 'service_advisor', 'tenant'),
		('receptions.reopen', 'owner', 'tenant'),
		('receptions.reopen', 'admin', 'tenant'),
		('signatures.capture', 'owner', 'tenant'),
		('signatures.capture', 'admin', 'tenant'),
		('signatures.capture', 'service_advisor', 'tenant'),
		('signatures.read', 'owner', 'tenant'),
		('signatures.read', 'admin', 'tenant'),
		('signatures.read', 'service_advisor', 'tenant'),
		('media.read', 'owner', 'tenant'),
		('media.read', 'admin', 'tenant'),
		('media.read', 'service_advisor', 'tenant'),
		('media.read', 'technician', 'assigned'),
		('media.upload', 'owner', 'tenant'),
		('media.upload', 'admin', 'tenant'),
		('media.upload', 'service_advisor', 'tenant'),
		('media.upload', 'technician', 'assigned'),
		('media.remove_unattached', 'owner', 'tenant'),
		('media.remove_unattached', 'admin', 'tenant'),
		('orders.read', 'owner', 'tenant'),
		('orders.read', 'admin', 'tenant'),
		('orders.read', 'service_advisor', 'tenant'),
		('orders.read', 'technician', 'assigned'),
		('orders.create', 'owner', 'tenant'),
		('orders.create', 'admin', 'tenant'),
		('orders.create', 'service_advisor', 'tenant'),
		('orders.transition', 'owner', 'tenant'),
		('orders.transition', 'admin', 'tenant'),
		('orders.transition', 'service_advisor', 'tenant'),
		('orders.assign', 'owner', 'tenant'),
		('orders.assign', 'admin', 'tenant'),
		('orders.assign', 'service_advisor', 'tenant'),
		('orders.cancel', 'owner', 'tenant'),
		('orders.cancel', 'admin', 'tenant'),
		('orders.cancel', 'service_advisor', 'tenant'),
		('orders.reopen', 'owner', 'tenant'),
		('orders.reopen', 'admin', 'tenant'),
		('order_items.read', 'owner', 'tenant'),
		('order_items.read', 'admin', 'tenant'),
		('order_items.read', 'service_advisor', 'tenant'),
		('order_items.read', 'technician', 'assigned'),
		('order_items.adjust_before_completion', 'owner', 'tenant'),
		('order_items.adjust_before_completion', 'admin', 'tenant'),
		('order_items.adjust_before_completion', 'service_advisor', 'tenant'),
		('warranty.override_before_completion', 'owner', 'tenant'),
		('warranty.override_before_completion', 'admin', 'tenant'),
		('warranty.override_before_completion', 'service_advisor', 'tenant'),
		('warranty.correct_after_completion', 'owner', 'tenant'),
		('warranty.correct_after_completion', 'admin', 'tenant'),
		('diagnostics.read', 'owner', 'tenant'),
		('diagnostics.read', 'admin', 'tenant'),
		('diagnostics.read', 'service_advisor', 'tenant'),
		('diagnostics.read', 'technician', 'assigned'),
		('diagnostics.write', 'owner', 'tenant'),
		('diagnostics.write', 'admin', 'tenant'),
		('diagnostics.write', 'service_advisor', 'tenant'),
		('diagnostics.write', 'technician', 'assigned'),
		('diagnostics.close', 'owner', 'tenant'),
		('diagnostics.close', 'admin', 'tenant'),
		('diagnostics.close', 'service_advisor', 'tenant'),
		('diagnostics.close', 'technician', 'assigned'),
		('catalog.read', 'owner', 'tenant'),
		('catalog.read', 'admin', 'tenant'),
		('catalog.read', 'service_advisor', 'tenant'),
		('catalog.read', 'technician', 'tenant'),
		('catalog.manage', 'owner', 'tenant'),
		('catalog.manage', 'admin', 'tenant'),
		('inventory.read', 'owner', 'tenant'),
		('inventory.read', 'admin', 'tenant'),
		('inventory.read', 'service_advisor', 'tenant'),
		('inventory.read', 'technician', 'tenant'),
		('inventory.movements.read', 'owner', 'tenant'),
		('inventory.movements.read', 'admin', 'tenant'),
		('inventory.movements.read', 'service_advisor', 'tenant'),
		('inventory.movements.read', 'technician', 'assigned'),
		('inventory.receive', 'owner', 'tenant'),
		('inventory.receive', 'admin', 'tenant'),
		('inventory.adjust', 'owner', 'tenant'),
		('inventory.adjust', 'admin', 'tenant'),
		('inventory.transfer', 'owner', 'tenant'),
		('inventory.transfer', 'admin', 'tenant'),
		('inventory.consume_assigned', 'owner', 'tenant'),
		('inventory.consume_assigned', 'admin', 'tenant'),
		('inventory.consume_assigned', 'service_advisor', 'tenant'),
		('inventory.consume_assigned', 'technician', 'assigned'),
		('quotes.propose_labor_adjustment', 'owner', 'tenant'),
		('quotes.propose_labor_adjustment', 'admin', 'tenant'),
		('quotes.propose_labor_adjustment', 'service_advisor', 'tenant'),
		('quotes.propose_labor_adjustment', 'technician', 'assigned'),
		('quotes.read', 'owner', 'tenant'),
		('quotes.read', 'admin', 'tenant'),
		('quotes.read', 'service_advisor', 'tenant'),
		('quotes.create', 'owner', 'tenant'),
		('quotes.create', 'admin', 'tenant'),
		('quotes.create', 'service_advisor', 'tenant'),
		('quotes.update_draft', 'owner', 'tenant'),
		('quotes.update_draft', 'admin', 'tenant'),
		('quotes.update_draft', 'service_advisor', 'tenant'),
		('quotes.override_price', 'owner', 'tenant'),
		('quotes.override_price', 'admin', 'tenant'),
		('quotes.override_price', 'service_advisor', 'tenant'),
		('quotes.send', 'owner', 'tenant'),
		('quotes.send', 'admin', 'tenant'),
		('quotes.send', 'service_advisor', 'tenant'),
		('quote_authorizations.read', 'owner', 'tenant'),
		('quote_authorizations.read', 'admin', 'tenant'),
		('quote_authorizations.read', 'service_advisor', 'tenant'),
		('quote_authorizations.record_manual', 'owner', 'tenant'),
		('quote_authorizations.record_manual', 'admin', 'tenant'),
		('quote_authorizations.record_manual', 'service_advisor', 'tenant'),
		('work_activities.read', 'owner', 'tenant'),
		('work_activities.read', 'admin', 'tenant'),
		('work_activities.read', 'service_advisor', 'tenant'),
		('work_activities.read', 'technician', 'assigned'),
		('work_activities.manage', 'owner', 'tenant'),
		('work_activities.manage', 'admin', 'tenant'),
		('work_activities.manage', 'service_advisor', 'tenant'),
		('work_activities.manage', 'technician', 'assigned'),
		('technician_logs.read', 'owner', 'tenant'),
		('technician_logs.read', 'admin', 'tenant'),
		('technician_logs.read', 'service_advisor', 'tenant'),
		('technician_logs.read', 'technician', 'assigned'),
		('technician_logs.create', 'owner', 'tenant'),
		('technician_logs.create', 'admin', 'tenant'),
		('technician_logs.create', 'technician', 'assigned'),
		('quality_checks.read', 'owner', 'tenant'),
		('quality_checks.read', 'admin', 'tenant'),
		('quality_checks.read', 'service_advisor', 'tenant'),
		('quality_checks.read', 'technician', 'assigned'),
		('quality_checks.perform', 'owner', 'tenant'),
		('quality_checks.perform', 'admin', 'tenant'),
		('quality_checks.perform', 'service_advisor', 'tenant'),
		('quality_checks.perform', 'technician', 'quality_control'),
		('deliveries.read', 'owner', 'tenant'),
		('deliveries.read', 'admin', 'tenant'),
		('deliveries.read', 'service_advisor', 'tenant'),
		('deliveries.complete', 'owner', 'tenant'),
		('deliveries.complete', 'admin', 'tenant'),
		('deliveries.complete', 'service_advisor', 'tenant'),
		('customer_payments.read', 'owner', 'tenant'),
		('customer_payments.read', 'admin', 'tenant'),
		('customer_payments.read', 'service_advisor', 'tenant'),
		('customer_payments.record', 'owner', 'tenant'),
		('customer_payments.record', 'admin', 'tenant'),
		('customer_payments.record', 'service_advisor', 'tenant'),
		('customer_payments.allocate', 'owner', 'tenant'),
		('customer_payments.allocate', 'admin', 'tenant'),
		('customer_payments.allocate', 'service_advisor', 'tenant'),
		('customer_payments.reverse', 'owner', 'tenant'),
		('customer_payments.reverse', 'admin', 'tenant'),
		('customer_payment_reconciliation.read', 'owner', 'tenant'),
		('customer_payment_reconciliation.read', 'admin', 'tenant'),
		('customer_payment_reconciliation.run', 'owner', 'tenant'),
		('customer_payment_reconciliation.run', 'admin', 'tenant'),
		('customer_access_tokens.read', 'owner', 'tenant'),
		('customer_access_tokens.read', 'admin', 'tenant'),
		('customer_access_tokens.read', 'service_advisor', 'tenant'),
		('customer_access_tokens.create', 'owner', 'tenant'),
		('customer_access_tokens.create', 'admin', 'tenant'),
		('customer_access_tokens.create', 'service_advisor', 'tenant'),
		('customer_access_tokens.revoke', 'owner', 'tenant'),
		('customer_access_tokens.revoke', 'admin', 'tenant'),
		('customer_access_tokens.revoke', 'service_advisor', 'tenant'),
		('messages.read', 'owner', 'tenant'),
		('messages.read', 'admin', 'tenant'),
		('messages.read', 'service_advisor', 'tenant'),
		('messages.send', 'owner', 'tenant'),
		('messages.send', 'admin', 'tenant'),
		('messages.send', 'service_advisor', 'tenant'),
		('reminders.manage', 'owner', 'tenant'),
		('reminders.manage', 'admin', 'tenant'),
		('reminders.manage', 'service_advisor', 'tenant'),
		('privacy_consents.read', 'owner', 'tenant'),
		('privacy_consents.read', 'admin', 'tenant'),
		('privacy_consents.read', 'service_advisor', 'tenant'),
		('privacy_consents.capture', 'owner', 'tenant'),
		('privacy_consents.capture', 'admin', 'tenant'),
		('privacy_consents.capture', 'service_advisor', 'tenant'),
		('data_subject_requests.create', 'owner', 'tenant'),
		('data_subject_requests.create', 'admin', 'tenant'),
		('data_subject_requests.create', 'service_advisor', 'tenant'),
		('data_subject_requests.read', 'owner', 'tenant'),
		('data_subject_requests.read', 'admin', 'tenant'),
		('data_subject_requests.resolve', 'owner', 'tenant'),
		('data_subject_requests.resolve', 'admin', 'tenant'),
		('privacy_data.export', 'owner', 'tenant'),
		('privacy_data.export', 'admin', 'tenant'),
		('privacy_data.anonymize_or_delete', 'owner', 'tenant'),
		('privacy_data.anonymize_or_delete', 'admin', 'tenant'),
		('privacy_incidents.manage', 'owner', 'tenant'),
		('privacy_incidents.manage', 'admin', 'tenant'),
		('subscription.read', 'owner', 'tenant'),
		('subscription.read', 'admin', 'tenant'),
		('subscription.manage', 'owner', 'tenant'),
		('legal_acceptances.read', 'owner', 'tenant'),
		('legal_acceptances.read', 'admin', 'tenant'),
		('legal_acceptances.accept_for_tenant', 'owner', 'tenant'),
		('dashboard.operational.read', 'owner', 'tenant'),
		('dashboard.operational.read', 'admin', 'tenant'),
		('dashboard.operational.read', 'service_advisor', 'tenant'),
		('dashboard.operational.read', 'technician', 'assigned'),
		('dashboard.business.read', 'owner', 'tenant'),
		('dashboard.business.read', 'admin', 'tenant'),
		('reports.operational.read', 'owner', 'tenant'),
		('reports.operational.read', 'admin', 'tenant'),
		('reports.operational.read', 'service_advisor', 'tenant'),
		('reports.financial.read', 'owner', 'tenant'),
		('reports.financial.read', 'admin', 'tenant'),
		('exports.operational.create', 'owner', 'tenant'),
		('exports.operational.create', 'admin', 'tenant'),
		('notifications.read', 'owner', 'tenant'),
		('notifications.read', 'admin', 'tenant'),
		('notifications.read', 'service_advisor', 'tenant'),
		('notifications.read', 'technician', 'tenant'),
		('notifications.preferences.update_self', 'owner', 'tenant'),
		('notifications.preferences.update_self', 'admin', 'tenant'),
		('notifications.preferences.update_self', 'service_advisor', 'tenant'),
		('notifications.preferences.update_self', 'technician', 'tenant'),
		('integrations.read', 'owner', 'tenant'),
		('integrations.read', 'admin', 'tenant'),
		('integrations.manage', 'owner', 'tenant'),
		('integrations.manage', 'admin', 'tenant')
	) AS canonical(permission_code, role_code, resource_scope)
	JOIN public.permissions p ON p.code = canonical.permission_code
	JOIN public.roles r ON r.code = canonical.role_code
	JOIN public.role_permissions rp ON rp.role_id = r.id AND rp.permission_id = p.id
	WHERE rp.resource_scope IS DISTINCT FROM canonical.resource_scope;

	IF v_mismatched > 0 THEN
		RAISE EXCEPTION 'RBAC_SEED_SCOPE_DRIFT: % existing role_permissions row(s) have a resource_scope different from RBAC_MATRIX_V1', v_mismatched;
	END IF;
END
$rbac_scope_drift_guard$;
--> statement-breakpoint

-- role_permissions (290 filas, RBAC_MATRIX_V1). Idempotente: la
-- guarda anterior ya garantizó que ninguna fila existente tiene un scope
-- distinto, por lo que DO NOTHING aquí solo omite reinserciones exactas.
INSERT INTO public.role_permissions (role_id, permission_id, resource_scope)
SELECT r.id, p.id, canonical.resource_scope
FROM (
	VALUES
		('workshop.read', 'owner', 'tenant'),
		('workshop.read', 'admin', 'tenant'),
		('workshop.read', 'service_advisor', 'tenant'),
		('workshop.read', 'technician', 'tenant'),
		('workshop.profile.update', 'owner', 'tenant'),
		('workshop.profile.update', 'admin', 'tenant'),
		('workshop.legal.update', 'owner', 'tenant'),
		('locations.read', 'owner', 'tenant'),
		('locations.read', 'admin', 'tenant'),
		('locations.read', 'service_advisor', 'tenant'),
		('locations.read', 'technician', 'tenant'),
		('locations.manage', 'owner', 'tenant'),
		('locations.manage', 'admin', 'tenant'),
		('memberships.read', 'owner', 'tenant'),
		('memberships.read', 'admin', 'tenant'),
		('memberships.invite_staff', 'owner', 'tenant'),
		('memberships.invite_staff', 'admin', 'tenant'),
		('memberships.manage_staff', 'owner', 'tenant'),
		('memberships.manage_staff', 'admin', 'tenant'),
		('roles.assign_staff', 'owner', 'tenant'),
		('roles.assign_staff', 'admin', 'tenant'),
		('roles.assign_admin', 'owner', 'tenant'),
		('roles.assign_owner', 'owner', 'tenant'),
		('ownership.transfer', 'owner', 'tenant'),
		('audit.read', 'owner', 'tenant'),
		('audit.read', 'admin', 'tenant'),
		('customers.read', 'owner', 'tenant'),
		('customers.read', 'admin', 'tenant'),
		('customers.read', 'service_advisor', 'tenant'),
		('customers.create', 'owner', 'tenant'),
		('customers.create', 'admin', 'tenant'),
		('customers.create', 'service_advisor', 'tenant'),
		('customers.update', 'owner', 'tenant'),
		('customers.update', 'admin', 'tenant'),
		('customers.update', 'service_advisor', 'tenant'),
		('customers.archive', 'owner', 'tenant'),
		('customers.archive', 'admin', 'tenant'),
		('vehicles.read', 'owner', 'tenant'),
		('vehicles.read', 'admin', 'tenant'),
		('vehicles.read', 'service_advisor', 'tenant'),
		('vehicles.read', 'technician', 'assigned'),
		('vehicles.create', 'owner', 'tenant'),
		('vehicles.create', 'admin', 'tenant'),
		('vehicles.create', 'service_advisor', 'tenant'),
		('vehicles.update', 'owner', 'tenant'),
		('vehicles.update', 'admin', 'tenant'),
		('vehicles.update', 'service_advisor', 'tenant'),
		('vehicle_owners.manage', 'owner', 'tenant'),
		('vehicle_owners.manage', 'admin', 'tenant'),
		('vehicle_owners.manage', 'service_advisor', 'tenant'),
		('appointments.read', 'owner', 'tenant'),
		('appointments.read', 'admin', 'tenant'),
		('appointments.read', 'service_advisor', 'tenant'),
		('appointments.manage', 'owner', 'tenant'),
		('appointments.manage', 'admin', 'tenant'),
		('appointments.manage', 'service_advisor', 'tenant'),
		('receptions.read', 'owner', 'tenant'),
		('receptions.read', 'admin', 'tenant'),
		('receptions.read', 'service_advisor', 'tenant'),
		('receptions.read', 'technician', 'assigned'),
		('receptions.create', 'owner', 'tenant'),
		('receptions.create', 'admin', 'tenant'),
		('receptions.create', 'service_advisor', 'tenant'),
		('receptions.update_open', 'owner', 'tenant'),
		('receptions.update_open', 'admin', 'tenant'),
		('receptions.update_open', 'service_advisor', 'tenant'),
		('receptions.close', 'owner', 'tenant'),
		('receptions.close', 'admin', 'tenant'),
		('receptions.close', 'service_advisor', 'tenant'),
		('receptions.reopen', 'owner', 'tenant'),
		('receptions.reopen', 'admin', 'tenant'),
		('signatures.capture', 'owner', 'tenant'),
		('signatures.capture', 'admin', 'tenant'),
		('signatures.capture', 'service_advisor', 'tenant'),
		('signatures.read', 'owner', 'tenant'),
		('signatures.read', 'admin', 'tenant'),
		('signatures.read', 'service_advisor', 'tenant'),
		('media.read', 'owner', 'tenant'),
		('media.read', 'admin', 'tenant'),
		('media.read', 'service_advisor', 'tenant'),
		('media.read', 'technician', 'assigned'),
		('media.upload', 'owner', 'tenant'),
		('media.upload', 'admin', 'tenant'),
		('media.upload', 'service_advisor', 'tenant'),
		('media.upload', 'technician', 'assigned'),
		('media.remove_unattached', 'owner', 'tenant'),
		('media.remove_unattached', 'admin', 'tenant'),
		('orders.read', 'owner', 'tenant'),
		('orders.read', 'admin', 'tenant'),
		('orders.read', 'service_advisor', 'tenant'),
		('orders.read', 'technician', 'assigned'),
		('orders.create', 'owner', 'tenant'),
		('orders.create', 'admin', 'tenant'),
		('orders.create', 'service_advisor', 'tenant'),
		('orders.transition', 'owner', 'tenant'),
		('orders.transition', 'admin', 'tenant'),
		('orders.transition', 'service_advisor', 'tenant'),
		('orders.assign', 'owner', 'tenant'),
		('orders.assign', 'admin', 'tenant'),
		('orders.assign', 'service_advisor', 'tenant'),
		('orders.cancel', 'owner', 'tenant'),
		('orders.cancel', 'admin', 'tenant'),
		('orders.cancel', 'service_advisor', 'tenant'),
		('orders.reopen', 'owner', 'tenant'),
		('orders.reopen', 'admin', 'tenant'),
		('order_items.read', 'owner', 'tenant'),
		('order_items.read', 'admin', 'tenant'),
		('order_items.read', 'service_advisor', 'tenant'),
		('order_items.read', 'technician', 'assigned'),
		('order_items.adjust_before_completion', 'owner', 'tenant'),
		('order_items.adjust_before_completion', 'admin', 'tenant'),
		('order_items.adjust_before_completion', 'service_advisor', 'tenant'),
		('warranty.override_before_completion', 'owner', 'tenant'),
		('warranty.override_before_completion', 'admin', 'tenant'),
		('warranty.override_before_completion', 'service_advisor', 'tenant'),
		('warranty.correct_after_completion', 'owner', 'tenant'),
		('warranty.correct_after_completion', 'admin', 'tenant'),
		('diagnostics.read', 'owner', 'tenant'),
		('diagnostics.read', 'admin', 'tenant'),
		('diagnostics.read', 'service_advisor', 'tenant'),
		('diagnostics.read', 'technician', 'assigned'),
		('diagnostics.write', 'owner', 'tenant'),
		('diagnostics.write', 'admin', 'tenant'),
		('diagnostics.write', 'service_advisor', 'tenant'),
		('diagnostics.write', 'technician', 'assigned'),
		('diagnostics.close', 'owner', 'tenant'),
		('diagnostics.close', 'admin', 'tenant'),
		('diagnostics.close', 'service_advisor', 'tenant'),
		('diagnostics.close', 'technician', 'assigned'),
		('catalog.read', 'owner', 'tenant'),
		('catalog.read', 'admin', 'tenant'),
		('catalog.read', 'service_advisor', 'tenant'),
		('catalog.read', 'technician', 'tenant'),
		('catalog.manage', 'owner', 'tenant'),
		('catalog.manage', 'admin', 'tenant'),
		('inventory.read', 'owner', 'tenant'),
		('inventory.read', 'admin', 'tenant'),
		('inventory.read', 'service_advisor', 'tenant'),
		('inventory.read', 'technician', 'tenant'),
		('inventory.movements.read', 'owner', 'tenant'),
		('inventory.movements.read', 'admin', 'tenant'),
		('inventory.movements.read', 'service_advisor', 'tenant'),
		('inventory.movements.read', 'technician', 'assigned'),
		('inventory.receive', 'owner', 'tenant'),
		('inventory.receive', 'admin', 'tenant'),
		('inventory.adjust', 'owner', 'tenant'),
		('inventory.adjust', 'admin', 'tenant'),
		('inventory.transfer', 'owner', 'tenant'),
		('inventory.transfer', 'admin', 'tenant'),
		('inventory.consume_assigned', 'owner', 'tenant'),
		('inventory.consume_assigned', 'admin', 'tenant'),
		('inventory.consume_assigned', 'service_advisor', 'tenant'),
		('inventory.consume_assigned', 'technician', 'assigned'),
		('quotes.propose_labor_adjustment', 'owner', 'tenant'),
		('quotes.propose_labor_adjustment', 'admin', 'tenant'),
		('quotes.propose_labor_adjustment', 'service_advisor', 'tenant'),
		('quotes.propose_labor_adjustment', 'technician', 'assigned'),
		('quotes.read', 'owner', 'tenant'),
		('quotes.read', 'admin', 'tenant'),
		('quotes.read', 'service_advisor', 'tenant'),
		('quotes.create', 'owner', 'tenant'),
		('quotes.create', 'admin', 'tenant'),
		('quotes.create', 'service_advisor', 'tenant'),
		('quotes.update_draft', 'owner', 'tenant'),
		('quotes.update_draft', 'admin', 'tenant'),
		('quotes.update_draft', 'service_advisor', 'tenant'),
		('quotes.override_price', 'owner', 'tenant'),
		('quotes.override_price', 'admin', 'tenant'),
		('quotes.override_price', 'service_advisor', 'tenant'),
		('quotes.send', 'owner', 'tenant'),
		('quotes.send', 'admin', 'tenant'),
		('quotes.send', 'service_advisor', 'tenant'),
		('quote_authorizations.read', 'owner', 'tenant'),
		('quote_authorizations.read', 'admin', 'tenant'),
		('quote_authorizations.read', 'service_advisor', 'tenant'),
		('quote_authorizations.record_manual', 'owner', 'tenant'),
		('quote_authorizations.record_manual', 'admin', 'tenant'),
		('quote_authorizations.record_manual', 'service_advisor', 'tenant'),
		('work_activities.read', 'owner', 'tenant'),
		('work_activities.read', 'admin', 'tenant'),
		('work_activities.read', 'service_advisor', 'tenant'),
		('work_activities.read', 'technician', 'assigned'),
		('work_activities.manage', 'owner', 'tenant'),
		('work_activities.manage', 'admin', 'tenant'),
		('work_activities.manage', 'service_advisor', 'tenant'),
		('work_activities.manage', 'technician', 'assigned'),
		('technician_logs.read', 'owner', 'tenant'),
		('technician_logs.read', 'admin', 'tenant'),
		('technician_logs.read', 'service_advisor', 'tenant'),
		('technician_logs.read', 'technician', 'assigned'),
		('technician_logs.create', 'owner', 'tenant'),
		('technician_logs.create', 'admin', 'tenant'),
		('technician_logs.create', 'technician', 'assigned'),
		('quality_checks.read', 'owner', 'tenant'),
		('quality_checks.read', 'admin', 'tenant'),
		('quality_checks.read', 'service_advisor', 'tenant'),
		('quality_checks.read', 'technician', 'assigned'),
		('quality_checks.perform', 'owner', 'tenant'),
		('quality_checks.perform', 'admin', 'tenant'),
		('quality_checks.perform', 'service_advisor', 'tenant'),
		('quality_checks.perform', 'technician', 'quality_control'),
		('deliveries.read', 'owner', 'tenant'),
		('deliveries.read', 'admin', 'tenant'),
		('deliveries.read', 'service_advisor', 'tenant'),
		('deliveries.complete', 'owner', 'tenant'),
		('deliveries.complete', 'admin', 'tenant'),
		('deliveries.complete', 'service_advisor', 'tenant'),
		('customer_payments.read', 'owner', 'tenant'),
		('customer_payments.read', 'admin', 'tenant'),
		('customer_payments.read', 'service_advisor', 'tenant'),
		('customer_payments.record', 'owner', 'tenant'),
		('customer_payments.record', 'admin', 'tenant'),
		('customer_payments.record', 'service_advisor', 'tenant'),
		('customer_payments.allocate', 'owner', 'tenant'),
		('customer_payments.allocate', 'admin', 'tenant'),
		('customer_payments.allocate', 'service_advisor', 'tenant'),
		('customer_payments.reverse', 'owner', 'tenant'),
		('customer_payments.reverse', 'admin', 'tenant'),
		('customer_payment_reconciliation.read', 'owner', 'tenant'),
		('customer_payment_reconciliation.read', 'admin', 'tenant'),
		('customer_payment_reconciliation.run', 'owner', 'tenant'),
		('customer_payment_reconciliation.run', 'admin', 'tenant'),
		('customer_access_tokens.read', 'owner', 'tenant'),
		('customer_access_tokens.read', 'admin', 'tenant'),
		('customer_access_tokens.read', 'service_advisor', 'tenant'),
		('customer_access_tokens.create', 'owner', 'tenant'),
		('customer_access_tokens.create', 'admin', 'tenant'),
		('customer_access_tokens.create', 'service_advisor', 'tenant'),
		('customer_access_tokens.revoke', 'owner', 'tenant'),
		('customer_access_tokens.revoke', 'admin', 'tenant'),
		('customer_access_tokens.revoke', 'service_advisor', 'tenant'),
		('messages.read', 'owner', 'tenant'),
		('messages.read', 'admin', 'tenant'),
		('messages.read', 'service_advisor', 'tenant'),
		('messages.send', 'owner', 'tenant'),
		('messages.send', 'admin', 'tenant'),
		('messages.send', 'service_advisor', 'tenant'),
		('reminders.manage', 'owner', 'tenant'),
		('reminders.manage', 'admin', 'tenant'),
		('reminders.manage', 'service_advisor', 'tenant'),
		('privacy_consents.read', 'owner', 'tenant'),
		('privacy_consents.read', 'admin', 'tenant'),
		('privacy_consents.read', 'service_advisor', 'tenant'),
		('privacy_consents.capture', 'owner', 'tenant'),
		('privacy_consents.capture', 'admin', 'tenant'),
		('privacy_consents.capture', 'service_advisor', 'tenant'),
		('data_subject_requests.create', 'owner', 'tenant'),
		('data_subject_requests.create', 'admin', 'tenant'),
		('data_subject_requests.create', 'service_advisor', 'tenant'),
		('data_subject_requests.read', 'owner', 'tenant'),
		('data_subject_requests.read', 'admin', 'tenant'),
		('data_subject_requests.resolve', 'owner', 'tenant'),
		('data_subject_requests.resolve', 'admin', 'tenant'),
		('privacy_data.export', 'owner', 'tenant'),
		('privacy_data.export', 'admin', 'tenant'),
		('privacy_data.anonymize_or_delete', 'owner', 'tenant'),
		('privacy_data.anonymize_or_delete', 'admin', 'tenant'),
		('privacy_incidents.manage', 'owner', 'tenant'),
		('privacy_incidents.manage', 'admin', 'tenant'),
		('subscription.read', 'owner', 'tenant'),
		('subscription.read', 'admin', 'tenant'),
		('subscription.manage', 'owner', 'tenant'),
		('legal_acceptances.read', 'owner', 'tenant'),
		('legal_acceptances.read', 'admin', 'tenant'),
		('legal_acceptances.accept_for_tenant', 'owner', 'tenant'),
		('dashboard.operational.read', 'owner', 'tenant'),
		('dashboard.operational.read', 'admin', 'tenant'),
		('dashboard.operational.read', 'service_advisor', 'tenant'),
		('dashboard.operational.read', 'technician', 'assigned'),
		('dashboard.business.read', 'owner', 'tenant'),
		('dashboard.business.read', 'admin', 'tenant'),
		('reports.operational.read', 'owner', 'tenant'),
		('reports.operational.read', 'admin', 'tenant'),
		('reports.operational.read', 'service_advisor', 'tenant'),
		('reports.financial.read', 'owner', 'tenant'),
		('reports.financial.read', 'admin', 'tenant'),
		('exports.operational.create', 'owner', 'tenant'),
		('exports.operational.create', 'admin', 'tenant'),
		('notifications.read', 'owner', 'tenant'),
		('notifications.read', 'admin', 'tenant'),
		('notifications.read', 'service_advisor', 'tenant'),
		('notifications.read', 'technician', 'tenant'),
		('notifications.preferences.update_self', 'owner', 'tenant'),
		('notifications.preferences.update_self', 'admin', 'tenant'),
		('notifications.preferences.update_self', 'service_advisor', 'tenant'),
		('notifications.preferences.update_self', 'technician', 'tenant'),
		('integrations.read', 'owner', 'tenant'),
		('integrations.read', 'admin', 'tenant'),
		('integrations.manage', 'owner', 'tenant'),
		('integrations.manage', 'admin', 'tenant')
) AS canonical(permission_code, role_code, resource_scope)
JOIN public.permissions p ON p.code = canonical.permission_code
JOIN public.roles r ON r.code = canonical.role_code
ON CONFLICT (role_id, permission_id) DO NOTHING;
--> statement-breakpoint

-- Guarda de conteos canónicos derivada de RBAC_MATRIX_V1. Aborta la
-- migración si el seed no produjo exactamente los conteos esperados.
DO $rbac_counts_guard$
DECLARE
	v_permissions_count integer;
	v_role_permissions_count integer;
	v_owner_tenant integer;
	v_admin_tenant integer;
	v_service_advisor_tenant integer;
	v_technician_tenant integer;
	v_technician_assigned integer;
	v_technician_quality_control integer;
BEGIN
	SELECT count(*) INTO v_permissions_count FROM public.permissions;
	IF v_permissions_count <> 103 THEN
		RAISE EXCEPTION 'RBAC_SEED_PERMISSIONS_COUNT_MISMATCH: expected=% found=%', 103, v_permissions_count;
	END IF;

	SELECT count(*) INTO v_role_permissions_count FROM public.role_permissions;
	IF v_role_permissions_count <> 290 THEN
		RAISE EXCEPTION 'RBAC_SEED_ROLE_PERMISSIONS_COUNT_MISMATCH: expected=% found=%', 290, v_role_permissions_count;
	END IF;

	SELECT count(*) INTO v_owner_tenant
	FROM public.role_permissions rp
	JOIN public.roles r ON r.id = rp.role_id
	WHERE r.code = 'owner' AND rp.resource_scope = 'tenant';
	IF v_owner_tenant <> 103 THEN
		RAISE EXCEPTION 'RBAC_SEED_COUNT_MISMATCH: role=% scope=% expected=% found=%', 'owner', 'tenant', 103, v_owner_tenant;
	END IF;
	SELECT count(*) INTO v_admin_tenant
	FROM public.role_permissions rp
	JOIN public.roles r ON r.id = rp.role_id
	WHERE r.code = 'admin' AND rp.resource_scope = 'tenant';
	IF v_admin_tenant <> 97 THEN
		RAISE EXCEPTION 'RBAC_SEED_COUNT_MISMATCH: role=% scope=% expected=% found=%', 'admin', 'tenant', 97, v_admin_tenant;
	END IF;
	SELECT count(*) INTO v_service_advisor_tenant
	FROM public.role_permissions rp
	JOIN public.roles r ON r.id = rp.role_id
	WHERE r.code = 'service_advisor' AND rp.resource_scope = 'tenant';
	IF v_service_advisor_tenant <> 65 THEN
		RAISE EXCEPTION 'RBAC_SEED_COUNT_MISMATCH: role=% scope=% expected=% found=%', 'service_advisor', 'tenant', 65, v_service_advisor_tenant;
	END IF;
	SELECT count(*) INTO v_technician_tenant
	FROM public.role_permissions rp
	JOIN public.roles r ON r.id = rp.role_id
	WHERE r.code = 'technician' AND rp.resource_scope = 'tenant';
	IF v_technician_tenant <> 6 THEN
		RAISE EXCEPTION 'RBAC_SEED_COUNT_MISMATCH: role=% scope=% expected=% found=%', 'technician', 'tenant', 6, v_technician_tenant;
	END IF;
	SELECT count(*) INTO v_technician_assigned
	FROM public.role_permissions rp
	JOIN public.roles r ON r.id = rp.role_id
	WHERE r.code = 'technician' AND rp.resource_scope = 'assigned';
	IF v_technician_assigned <> 18 THEN
		RAISE EXCEPTION 'RBAC_SEED_COUNT_MISMATCH: role=% scope=% expected=% found=%', 'technician', 'assigned', 18, v_technician_assigned;
	END IF;
	SELECT count(*) INTO v_technician_quality_control
	FROM public.role_permissions rp
	JOIN public.roles r ON r.id = rp.role_id
	WHERE r.code = 'technician' AND rp.resource_scope = 'quality_control';
	IF v_technician_quality_control <> 1 THEN
		RAISE EXCEPTION 'RBAC_SEED_COUNT_MISMATCH: role=% scope=% expected=% found=%', 'technician', 'quality_control', 1, v_technician_quality_control;
	END IF;
END
$rbac_counts_guard$;
--> statement-breakpoint

-- END GENERATED RBAC V1

RESET ROLE;
